### ISSUE TITLE
deployment failed

### ISSUE THREAD

**Issue by raji2004** [raji2004/RefreeG-Platform#8]
[2024-10-06T14:10:44.142Z]  @firebase/firestore: Firestore (10.14.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=permission-denied]: 7 PERMISSION_DENIED: Permission denied on resource project "refreeg-platform".

⨯ Static worker exited with code: null and signal: SIGTERM

[2024-10-06T14:11:44.799Z]  @firebase/firestore: Firestore (10.14.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=permission-denied]: 7 PERMISSION_DENIED: Permission denied on resource project "refreeg-platform"

Static worker exited with code: null and signal: SIGTERM
> Build error occurred
Error: Static page generation for /api/admin is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (/vercel/path0/node_modules/next/dist/build/index.js:279:27)
    at /vercel/path0/node_modules/next/dist/lib/worker.js:95:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /vercel/path0/node_modules/next/dist/export/index.js:450:20
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:154:20)
    at async /vercel/path0/node_modules/next/dist/export/index.js:448:24
    at async Promise.all (index 2)
    at async exportAppImpl (/vercel/path0/node_modules/next/dist/export/index.js:440:21)
    at async /vercel/path0/node_modules/next/dist/export/index.js:623:16
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:154:20)
Error: Command "npm run build" exited with 1

**Comment by raji2004** [comment]
these are the deployment errors
